[package]
name = "sussy_ducky_bot"
version = "0.1.0"
edition = "2021"


[dependencies]
lambda_http = "0.13"
lambda_runtime = "0.13"
reqwest = { version = "0.12", features = [
    "multipart",
    "json",
    "native-tls-vendored",
], default-features = false }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
] }
teloxide = { version = "0.13", features = ["macros"] }
async-openai = { git = "https://github.com/64bit/async-openai", rev = "05d5a1b4fa6476829dd1a34447b80279cf89d4f8" }

[package.metadata.lambda.deploy]
memory = 128      # Function's memory
timeout = 60      # Function's execution timeout
env_file = ".env" # File to load environment variables from
