[package]
name = "sussy_ducky_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { git = "https://github.com/teloxide/teloxide", features = [
    "macros",
] } # we need some features from the master branch
log = "^0.4"
pretty_env_logger = "^0.5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dotenv = "^0.15"
reqwest = { version = "^0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "^0.22"
rand = "^0.8"
enum-iterator = "2.1.0"
ollama-rs = { version = "0.2.0", features = ["stream"] }
tokio-stream = "0.1.15"
image = "0.25.1"
aws-config = { version = "1.5", features = ["behavior-version-latest"] }
aws-sdk-bedrockruntime = "^1.36"
regex = "1.10.5"
comfyui-api = { git = "https://github.com/capslock/stable-diffusion-bot", version = "0.2.1" }
# indicatif = "0.17.8"
