name: Build, Test, and Deploy to AWS Lambda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Job to build and test Rust code
  rust-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Rust project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  # # Job to build and deploy to AWS Lambda (only if rust-check passes)
  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   needs: rust-check  # Only runs if the 'rust-check' job passes

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install cargo-lambda
  #       run: |
  #         cargo install cargo-lambda

  #     - name: Build for AWS Lambda
  #       run: cargo lambda build --release # we won't build for arm64 since installing cargo-labda through cargo doesn't support it

  #     - name: Deploy Lambda Function
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_REGION: ${{ secrets.AWS_REGION }}
  #       run: cargo lambda deploy
